name: "cm-push"
version: "0.10.4"
usage: "Please see https://github.com/chartmuseum/helm-push for usage"
description: "Push chart package to ChartMuseum"
command: "$HELM_PLUGIN_DIR/bin/helm-cm-push"
downloaders:
- command: "bin/helm-cm-push"
  protocols:
  - "cm"
useTunnel: false
hooks:
  install: "cd C:\\Users\Mike~1\\AppData\\Roaming\\helm\\plugins\\helm-push\\scripts\\install_plugin.sh"
  update: "cd C:\\Users\\Mike~1\\AppData\\Roaming\\helm\\plugins\\helm-push\\scripts\\install_plugin.sh"
